alter table bw_xboard_board drop column g_read;
alter table bw_xboard_board drop column g_write;
alter table bw_xboard_board drop column g_comment;
alter table bw_xboard_board drop column m_read;
alter table bw_xboard_board drop column m_write;
alter table bw_xboard_board drop column m_comment;
alter table bw_xboard_board drop column a_read;
alter table bw_xboard_board drop column a_write;
alter table bw_xboard_board drop column a_comment;
alter table bw_xboard_board add column g_read tinyint(1) not null default 1;
alter table bw_xboard_board add column m_read tinyint(1) not null default 1;
alter table bw_xboard_board add column a_read tinyint(1) not null default 0;
alter table bw_xboard_board add column g_write tinyint(1) not null default 1;
alter table bw_xboard_board add column m_write tinyint(1) not null default 1;
alter table bw_xboard_board add column a_write tinyint(1) not null default 0;
alter table bw_xboard_board add column g_comment tinyint(1) not null default 1;
alter table bw_xboard_board add column m_comment tinyint(1) not null default 1;
alter table bw_xboard_board add column a_comment tinyint(1) not null default 0;
alter table bw_group drop column g_sub;
alter table bw_group drop column g_board;
alter table bw_group drop column m_sub;
alter table bw_group drop column m_board;
alter table bw_group drop column a_sub;
alter table bw_group drop column a_board;
alter table bw_group add column g_sub tinyint(1) not null default 0;
alter table bw_group add column m_sub tinyint(1) not null default 0;
alter table bw_group add column a_sub tinyint(1) not null default 0;
alter table bw_group add column g_board tinyint(1) not null default 0;
alter table bw_group add column m_board tinyint(1) not null default 0;
alter table bw_group add column a_board tinyint(1) not null default 0;
alter table bw_xboard_board modify column allow_recom tinyint(1) not null default 1;
alter table bw_xboard_board modify column allow_html tinyint(1) not null default 1;
alter table bw_xboard_board modify column allow_category tinyint(1) not null default 1;
alter table bw_xboard_board modify column allow_attach tinyint(1) not null default 1;
alter table bw_xboard_board add column is_imgboard2 tinyint(1) not null default 0 after is_imgboard;
update bw_xboard_board set is_imgboard2 = 1 where is_imgboard = 'Y';
alter table bw_xboard_board drop column is_imgboard;
alter table bw_xboard_board change column is_imgboard2 is_imgboard tinyint(1) not null default 0;
alter table bw_xboard_board drop column allow_reply;
alter table bw_xboard_recom drop primary key;
alter table bw_xboard_recom add primary key (article_id, uid);
alter table bw_xboard_bookmark add column seq smallint unsigned not null default 0;
alter table bw_group add column seq smallint unsigned not null default 0 after type;
alter table bw_xboard_board add column seq smallint unsigned not null default 0 after is_anonboard;
alter table bw_xboard_header add column has_attach tinyint(1) not null default '0' after comments;
alter table bw_xboard_header add column has_poll tinyint(1) not null default '0' after has_attach;
alter table bw_xboard_header add column has_ tinyint(1) not null default '0' after has_;
alter table bw_xboard_board add column g_tag tinyint(1) not null default 1;
alter table bw_xboard_board add column m_tag tinyint(1) not null default 1;
alter table bw_xboard_board add column a_tag tinyint(1) not null default 0;
